### ISSUE TITLE
Support injecting a custom exception handler

### ISSUE THREAD

**Issue by danschmidt5189** [tomas-zemres/syntax-feature-try#5]
Support for new type checkers has come up twice now - once for Moose::Util::TypeConstraints (#4) and once for [Type::Tiny](https://rt.cpan.org/Public/Bug/Display.html?id=99388).

I second @tobyink 's suggestion (on CPAN, see link) to add Type::Tiny support, and I agree that a general solution would be better than adding another one-off fix.

I think the syntax suggested in the CPAN issue is great - control on a package-level basis is really nice. But I think that by far the more common use-case will be to set a global (application / process-wide) handler.

Some ideas:

```perl
# Set a custom catcher in the current package:
use syntax try => { exception_handler => \&my_handler };

# Set a custom catcher globally for your app:
$Syntax::Feature::Try::exception_handler = \&my_handler;

# Catcher signature:
sub my_handler {
    my ($exception, $catch_name, $default_handler) = @_;
    # Return truthy / falsey to indicate that the exception
    # should / should not be caught. To use the original
    # logic, call $default_handler->($exception, $catch_name)
}
```

**Comment by tomas-zemres** [comment]
Are you happy with this solution?
https://github.com/tomas-zemres/syntax-feature-try/commit/5dacef590a111d8d20257bcc11bd06fb5993ed16

**Comment by danschmidt5189** [comment]
:+1: Lovely! Thank you for addressing this so quickly.
